contentDir = 'content/zh'
languageCode = 'zh-Hans-CN'
languageName = '中文'
weight = 2

title = 'Blue Tress'
copyright = '版权所有'

[author]
    name = "Yao"
    description = "生活在成都的程序员，热爱大自然"
    email = "tracyao(at)outlook.com"
